/**
 * AWS Bedrock Provider Template
 * Access Claude and other models via AWS Bedrock
 */

import type { ProviderTemplate } from '../template.js';

export const bedrockTemplate: ProviderTemplate = {
  id: 'bedrock',
  displayName: 'AWS Bedrock',
  description: 'Access Claude models via AWS Bedrock',
  category: 'cloud',
  icon: 'aws',
  fields: [
    {
      key: 'auth_method',
      label: 'Authentication Method',
      type: 'select',
      secret: false,
      required: true,
      options: [
        { value: 'iam_keys', label: 'IAM Access Keys', description: 'Use AWS access key and secret' },
        { value: 'iam_role', label: 'IAM Role', description: 'Use instance role (EC2/ECS/Lambda)' },
        { value: 'profile', label: 'AWS Profile', description: 'Use named profile from ~/.aws/credentials' },
      ],
      default: 'iam_keys',
    },
    {
      key: 'aws_access_key_id',
      label: 'AWS Access Key ID',
      type: 'password',
      secret: true,
      required: true,
      placeholder: 'AKIA...',
      help: 'Your AWS access key ID',
      pattern: '^AKIA[A-Z0-9]{16}$',
      patternError: 'Invalid AWS access key ID format',
      showWhen: { field: 'auth_method', equals: 'iam_keys' },
    },
    {
      key: 'aws_secret_access_key',
      label: 'AWS Secret Access Key',
      type: 'password',
      secret: true,
      required: true,
      placeholder: 'Your secret key...',
      help: 'Your AWS secret access key',
      showWhen: { field: 'auth_method', equals: 'iam_keys' },
    },
    {
      key: 'aws_profile',
      label: 'AWS Profile Name',
      type: 'text',
      secret: false,
      required: true,
      placeholder: 'default',
      help: 'Named profile from ~/.aws/credentials',
      showWhen: { field: 'auth_method', equals: 'profile' },
    },
    {
      key: 'aws_region_name',
      label: 'AWS Region',
      type: 'select',
      secret: false,
      required: true,
      options: [
        { value: 'us-east-1', label: 'US East (N. Virginia)', description: 'us-east-1' },
        { value: 'us-west-2', label: 'US West (Oregon)', description: 'us-west-2' },
        { value: 'eu-west-1', label: 'EU (Ireland)', description: 'eu-west-1' },
        { value: 'eu-central-1', label: 'EU (Frankfurt)', description: 'eu-central-1' },
        { value: 'ap-northeast-1', label: 'Asia Pacific (Tokyo)', description: 'ap-northeast-1' },
        { value: 'ap-southeast-1', label: 'Asia Pacific (Singapore)', description: 'ap-southeast-1' },
        { value: 'ap-southeast-2', label: 'Asia Pacific (Sydney)', description: 'ap-southeast-2' },
      ],
      default: 'us-east-1',
    },
    {
      key: 'model',
      label: 'Model',
      type: 'select',
      secret: false,
      required: true,
      options: [
        { value: 'anthropic.claude-opus-4-20250514-v1:0', label: 'Claude Opus 4', description: 'Most capable' },
        { value: 'anthropic.claude-sonnet-4-20250514-v1:0', label: 'Claude Sonnet 4', description: 'Balanced' },
        { value: 'anthropic.claude-3-5-sonnet-20241022-v2:0', label: 'Claude 3.5 Sonnet v2', description: 'Fast, capable' },
        { value: 'anthropic.claude-3-5-haiku-20241022-v1:0', label: 'Claude 3.5 Haiku', description: 'Fastest' },
        { value: 'anthropic.claude-3-opus-20240229-v1:0', label: 'Claude 3 Opus', description: 'Previous flagship' },
        { value: 'anthropic.claude-3-sonnet-20240229-v1:0', label: 'Claude 3 Sonnet', description: 'Previous generation' },
        { value: 'anthropic.claude-3-haiku-20240307-v1:0', label: 'Claude 3 Haiku', description: 'Previous fast model' },
      ],
      default: 'anthropic.claude-sonnet-4-20250514-v1:0',
    },
    {
      key: 'max_tokens',
      label: 'Max Output Tokens',
      type: 'number',
      secret: false,
      required: false,
      default: 4096,
      min: 1,
      max: 200000,
      help: 'Maximum tokens in the response',
    },
  ],
  litellmTemplate: {
    model_name: '{{display_name}}',
    litellm_params: {
      model: 'bedrock/{{model}}',
      aws_region_name: '{{aws_region_name}}',
      aws_access_key_id: '{{aws_access_key_id}}',
      aws_secret_access_key: '{{aws_secret_access_key}}',
      max_tokens: '{{max_tokens}}',
    },
  },
  validatorId: 'bedrock',
  docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html',
  setupSteps: [
    'Sign in to AWS Console and go to Bedrock',
    'Request model access for Claude models in your region',
    'Create an IAM user with bedrock:InvokeModel permission',
    'Generate access keys for the IAM user',
    'Paste the credentials above',
  ],
  supportsStreaming: true,
  supportsFunctionCalling: true,
  defaultModel: 'anthropic.claude-sonnet-4-20250514-v1:0',
};
